// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAP_Integrator_MVP_EF.Data;

#nullable disable

namespace SAP_Integrator_MVP_EF.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230919082058_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SAP_Integrator_MVP_EF.shared.BillingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SAP_ObjectCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BillingTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cancel Cash Sale",
                            Name = "SV",
                            SAP_ObjectCode = 13
                        },
                        new
                        {
                            Id = 2,
                            Description = "Invoice",
                            Name = "ZID1",
                            SAP_ObjectCode = 13
                        },
                        new
                        {
                            Id = 3,
                            Description = "Credit for Returns",
                            Name = "ZID4",
                            SAP_ObjectCode = 14
                        },
                        new
                        {
                            Id = 4,
                            Description = "Credit Ret W / O Ref",
                            Name = "ZRE1",
                            SAP_ObjectCode = 14
                        },
                        new
                        {
                            Id = 5,
                            Description = "RSS Invoice",
                            Name = "ZRSS",
                            SAP_ObjectCode = 13
                        },
                        new
                        {
                            Id = 6,
                            Description = "Van Sales Cash Inv.",
                            Name = "ZVAN",
                            SAP_ObjectCode = 13
                        },
                        new
                        {
                            Id = 7,
                            Description = "ZID7",
                            Name = "ZID7",
                            SAP_ObjectCode = 13
                        },
                        new
                        {
                            Id = 8,
                            Description = "ZID8",
                            Name = "ZID8",
                            SAP_ObjectCode = 13
                        },
                        new
                        {
                            Id = 9,
                            Description = "ZID9",
                            Name = "ZID9",
                            SAP_ObjectCode = 13
                        },
                        new
                        {
                            Id = 10,
                            Description = "ZRS1",
                            Name = "ZRS1",
                            SAP_ObjectCode = 13
                        });
                });

            modelBuilder.Entity("SAP_Integrator_MVP_EF.shared.Sales_Invoice.SalesInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BUnitId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("BillingTypeId")
                        .HasColumnType("int");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DocDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocNum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PurchaseOrderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SalesOrderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SalesmanId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillingTypeId");

                    b.ToTable("SalesInvoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BUnitId = 1,
                            BillingTypeId = 3,
                            CardCode = "UIC12345",
                            CardName = "NCCC",
                            DocDate = new DateTime(2023, 9, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DocDueDate = new DateTime(2023, 9, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DocNum = "SI12345",
                            PurchaseOrderNo = "PO12345",
                            SalesOrderNo = "SO12345",
                            SalesmanId = 1
                        },
                        new
                        {
                            Id = 2,
                            BUnitId = 12,
                            BillingTypeId = 4,
                            CardCode = "UIC12346",
                            CardName = "NCCC",
                            DocDate = new DateTime(2023, 9, 19, 16, 20, 58, 110, DateTimeKind.Local).AddTicks(1531),
                            DocDueDate = new DateTime(2023, 9, 19, 16, 20, 58, 110, DateTimeKind.Local).AddTicks(1531),
                            DocNum = "SI12346",
                            PurchaseOrderNo = "PO12346",
                            SalesOrderNo = "SO12346",
                            SalesmanId = 11
                        });
                });

            modelBuilder.Entity("SAP_Integrator_MVP_EF.shared.Sales_Invoice.SalesInvoice", b =>
                {
                    b.HasOne("SAP_Integrator_MVP_EF.shared.BillingType", "BillingType")
                        .WithMany()
                        .HasForeignKey("BillingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingType");
                });
#pragma warning restore 612, 618
        }
    }
}
